### ISSUE TITLE
Activating extension bruno-api-client.bruno failed due to an error: Cannot find module 'lodash'

### ISSUE THREAD

**Issue by bennieboj** [usebruno/bruno-ide-extensions#5]
![271923798-1711d329-1d3d-475b-8e9b-25c08b38051d](https://github.com/usebruno/bruno-ide-extensions/assets/4215739/ddfb3b8f-d53e-4acc-98b5-73cf0b68b565)

vscode version:
Version: 1.82.2
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:55:25.390Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

extension version: v3.1.0

Extension host logs:
```
2023-10-05 13:20:01.801 [info] ExtensionService#_doActivateExtension bruno-api-client.bruno, startup: false, activationEvent: 'onView:brunoPanel'
2023-10-05 13:20:01.972 [error] Activating extension bruno-api-client.bruno failed due to an error:
2023-10-05 13:20:01.972 [error] Error: Cannot find module 'lodash'
Require stack:
- c:\path\to\programs\vscode\VSCode-win32-x64\data\extensions\bruno-api-client.bruno-3.1.0\src\utils\bru.js
- c:\path\to\programs\vscode\VSCode-win32-x64\data\extensions\bruno-api-client.bruno-3.1.0\src\panel.js
- c:\path\to\programs\vscode\VSCode-win32-x64\data\extensions\bruno-api-client.bruno-3.1.0\src\extension.js
- c:\path\to\programs\vscode\VSCode-win32-x64\resources\app\out\vs\loader.js
- c:\path\to\programs\vscode\VSCode-win32-x64\resources\app\out\bootstrap-amd.js
- c:\path\to\programs\vscode\VSCode-win32-x64\resources\app\out\bootstrap-fork.js
- 
	at Module._resolveFilename (node:internal/modules/cjs/loader:1129:15)
	at s._resolveFilename (node:electron/js2c/utility_init:2:2786)
	at Module._load (node:internal/modules/cjs/loader:974:27)
	at f._load (node:electron/js2c/asar_bundle:2:13377)
	at c._load (c:\path\to\programs\vscode\VSCode-win32-x64\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:135:5630)
	at m._load (c:\path\to\programs\vscode\VSCode-win32-x64\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:132:29116)
	at D._load (c:\path\to\programs\vscode\VSCode-win32-x64\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:19764)
	at Module.require (node:internal/modules/cjs/loader:1195:19)
	at g (c:\path\to\programs\vscode\VSCode-win32-x64\resources\app\out\vs\loader.js:4:647)
	at Object.<anonymous> (c:\path\to\programs\vscode\VSCode-win32-x64\data\extensions\bruno-api-client.bruno-3.1.0\src\utils\bru.js:1:73)
	at u._compile (c:\path\to\programs\vscode\VSCode-win32-x64\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
	at Module.load (node:internal/modules/cjs/loader:1171:32)
	at Module._load (node:internal/modules/cjs/loader:1012:12)
	at f._load (node:electron/js2c/asar_bundle:2:13377)
	at c._load (c:\path\to\programs\vscode\VSCode-win32-x64\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:135:5630)
	at m._load (c:\path\to\programs\vscode\VSCode-win32-x64\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:132:29116)
	at D._load (c:\path\to\programs\vscode\VSCode-win32-x64\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:19764)
	at Module.require (node:internal/modules/cjs/loader:1195:19)
	at g (c:\path\to\programs\vscode\VSCode-win32-x64\resources\app\out\vs\loader.js:4:647)
	at Object.<anonymous> (c:\path\to\programs\vscode\VSCode-win32-x64\data\extensions\bruno-api-client.bruno-3.1.0\src\panel.js:3:23)
	at u._compile (c:\path\to\programs\vscode\VSCode-win32-x64\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
	at Module.load (node:internal/modules/cjs/loader:1171:32)
	at Module._load (node:internal/modules/cjs/loader:1012:12)
	at f._load (node:electron/js2c/asar_bundle:2:13377)
	at c._load (c:\path\to\programs\vscode\VSCode-win32-x64\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:135:5630)
	at m._load (c:\path\to\programs\vscode\VSCode-win32-x64\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:132:29116)
	at D._load (c:\path\to\programs\vscode\VSCode-win32-x64\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:19764)
	at Module.require (node:internal/modules/cjs/loader:1195:19)
	at g (c:\path\to\programs\vscode\VSCode-win32-x64\resources\app\out\vs\loader.js:4:647)
	at Object.<anonymous> (c:\path\to\programs\vscode\VSCode-win32-x64\data\extensions\bruno-api-client.bruno-3.1.0\src\extension.js:2:20)
	at u._compile (c:\path\to\programs\vscode\VSCode-win32-x64\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
	at Module.load (node:internal/modules/cjs/loader:1171:32)
	at Module._load (node:internal/modules/cjs/loader:1012:12)
	at f._load (node:electron/js2c/asar_bundle:2:13377)
	at c._load (c:\path\to\programs\vscode\VSCode-win32-x64\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:135:5630)
	at m._load (c:\path\to\programs\vscode\VSCode-win32-x64\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:132:29116)
	at D._load (c:\path\to\programs\vscode\VSCode-win32-x64\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:19764)
	at Module.require (node:internal/modules/cjs/loader:1195:19)
	at require (node:internal/modules/cjs/helpers:110:18)
	at Function.i [as __$__nodeRequire] (c:\path\to\programs\vscode\VSCode-win32-x64\resources\app\out\vs\loader.js:5:98)
	at n.rb (c:\path\to\programs\vscode\VSCode-win32-x64\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:132:30295)
	at async Promise.all (index 0)
```

When I'm going an npm install in `programs\vscode\VSCode-win32-x64\data\extensions\bruno-api-client.bruno-3.1.0` I don't see any logs anymore in the extension host logs:
```
2023-10-05 14:16:04.671 [info] Extension host with pid 17840 started
2023-10-05 14:16:04.672 [info] Skipping acquiring lock for c:\path\to\programs\vscode\VSCode-win32-x64\data\user-data\User\workspaceStorage\4d6d6ab3fd626c36fcd02f86abe955e9.
2023-10-05 14:16:04.861 [info] ExtensionService#_doActivateExtension bruno-api-client.bruno, startup: false, activationEvent: 'onView:brunoPanel'
2023-10-05 14:16:12.085 [info] ExtensionService#_doActivateExtension vscode.extension-editing, startup: false, activationEvent: 'onLanguage:markdown'
2023-10-05 14:16:12.174 [info] ExtensionService#_doActivateExtension vscode.markdown-language-features, startup: false, activationEvent: 'onLanguage:markdown'
2023-10-05 14:16:12.316 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2023-10-05 14:16:12.372 [info] ExtensionService#_doActivateExtension vscode.json-language-features, startup: false, activationEvent: 'onLanguage:json'
2023-10-05 14:16:12.510 [info] ExtensionService#_doActivateExtension vscode.npm, startup: false, activationEvent: 'onLanguage:json'
2023-10-05 14:16:12.663 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2023-10-05 14:16:12.693 [info] ExtensionService#_doActivateExtension ms-vscode.test-adapter-converter, startup: true, activationEvent: '*', root cause: hbenl.vscode-test-explorer
2023-10-05 14:16:12.756 [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
2023-10-05 14:16:12.947 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2023-10-05 14:16:13.168 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2023-10-05 14:16:13.313 [info] ExtensionService#_doActivateExtension hbenl.vscode-test-explorer, startup: true, activationEvent: '*'
2023-10-05 14:16:13.727 [info] ExtensionService#_doActivateExtension kavod-io.vscode-jest-test-adapter, startup: true, activationEvent: '*'
2023-10-05 14:16:14.388 [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
2023-10-05 14:16:14.558 [info] ExtensionService#_doActivateExtension vscode.markdown-math, startup: false, activationEvent: 'api', root cause: vscode.markdown-language-features
2023-10-05 14:16:15.244 [info] Eager extensions activated
2023-10-05 14:16:15.256 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2023-10-05 14:16:15.295 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2023-10-05 14:16:15.674 [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-wsl-recommender, startup: false, activationEvent: 'onStartupFinished'
```
Not sure if doing an npm install should be needed though?

I'm seeing in the developer tools that the extension is active:
"[Extension Host] Congratulations, your extension "bruno" is now active!"
Any more logs I can give?

**Comment by ZaneH** [comment]
+1, ran into this on macOS Sonoma with VSCode v1.85.1. I tried reinstalling the plugin, no dice.

**Comment by kirstyannepollock** [comment]
same here on Linux (Ubunti 20.04)
`2023-12-22 09:49:35.694 [error] Activating extension bruno-api-client.bruno failed due to an error:
2023-12-22 09:49:35.694 [error] Error: Cannot find module 'lodash'`

**Comment by wouter-leistra** [comment]
Same issue here... My bruno panel just states: "There is no data provider registered..."

**Comment by shaktisingh-msft** [comment]
![image](https://github.com/usebruno/bruno-ide-extensions/assets/110027638/862ee56f-ba00-4cf8-9445-e0c4fa4390a3)
Same issue on my VSC 1.87.2

**Comment by peledies** [comment]
Im kind of surprised that this vscode extension is advertised on the main bruno site. This thing does not work at all and this issue has been open for over a year. 

Sure would be nice to use bruno in my IDE...maybe some day.

**Comment by hong-tm** [comment]
> Im kind of surprised that this vscode extension is advertised on the main bruno site. This thing does not work at all and this issue has been open for over a year.

```
Features
This plugin provides the syntax highlight feature for .bru files
```

I think for now only support the syntax highlight
